---
title: "Exercise 3"
subtitle: "Fortgeschrittene Statistische Software für NF - SS 2022/23"
author: "Valentin Mesmer (12578200), Tim-Luis Hartenfels (12597574), Junis Al Attar (12574322)"
date: "`r Sys.Date()`"
output: pdf_document
---


## Exercise 1: Initializing git (4 Points)

d) Strengths of Git:

    1. Git enables every developer working on a project to have a copy of the repository at a special version, so he can work offline and synchronize with the repository when connected to the internet
    
    2. Developers can create branches to work on different features or versions and merge them later.
    

    Weaknesses of Git:

      1. It may be hard to learn git, because at the beginning learners may have some problems to create an account and to understand the connection between e.g. GitHub and their local version.
    
      2. Git tracks the changes in files line by line, which is really great for code, but really bad for large files like images, zips or binaries.
      
      
## Exercise 2: Putting your Repository on GitHub (3.5 Points)

## Exercise 3: Baby-Names in Munich (4.5 Points)

## Exercise 4: Chat GPT + apply (3 points)
